pipeline {
    agent any
    
    tools {
        maven "m3"   
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/bllexe/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }

    post {
        success {
            echo '🎉 Build & Tests succeeded!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}
